### PR TITLE
Added replace-script-tags and release gulp tasks

### PR DESCRIPTION
**Pull request by tylerferguson**
Had to make unit test task and e2e test task run sync

### CODE REVIEW

**Comment by ghost** [comment]
:shipit:
I'll rebase my SASS work onto this branch. We can use a WebStorm watcher to recompile SASS during development, meaning we only want gulp to run SASS compilation as part of a release build. The CSS will have to be copied over to cordova along with the index.html and the minified JavaScript. I don't think we need to bother minifying the CSS? Can we discuss?

**Comment by tylerferguson** [comment]
I'm not 100% on the benefits of minifying CSS. Is it noticeable? The WebStorm idea sounds fine.

**Comment by ghost** [comment]
I'd say we don't need to minify the CSS at the moment. We can do it if we see payload size issues, but I'm guessing that's unlikely because:
- When we're serving files over the wire, that will be within Man's network where bandwidth will be (hopefully) higher than on the internet.
- When we're running on a mobile device files are served from the device's file system, so there's nothing being sent over the wire anyway.

**Comment by DavidThomasSL** [comment]
It would be good if we could rename webserver-start/stop as these names aren't really accurate. You could also rename 'stream' while you're at it.

**Pull request merged**
